version: '3'
services:
    app:
        build: .
        entrypoint: .docker/entrypoint.sh
        container_name: apisales-app
        ports:
            - "8888:8888"
        volumes:
            - .:/home/node/app
        depends_on:
            - db
            - redis

    db:
        build: .docker/postgres
        container_name: apisales-db
        restart: always
        tty: true
        ports:
            - "5432:5432"
        volumes:
            - .docker/dbdata:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=apisales

    redis:
        image: bitnami/redis:latest
        container_name: apisales-redis
        environment:
            - ALLOW_EMPTY_PASSWORD=yes

    pgadmin:
        image: dpage/pgadmin4
        container_name: apisales-pgadmin
        tty: true
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=admin
        ports:
            - '8000:80'
        depends_on:
            - db

